#!/bin/sh

set -u # exit on unset var
set -e # exit on non-true return value
cd $(dirname ${BASH_SOURCE[0]}) # change to project root for relative paths

########

if [ "$#" -ne 2 ]; then
	echo "Usage:"
	echo "./run <number_of_entries> <number_of_processors>"
	echo ""
	exit 1
else
    app/console processor:setup $1 # setup data set
    for ((c = 1; c <= $2; c++)); do # spawn processors
        app/console processor:run ${c} &
    done
    wait
fi
